[package]
name = "sumi-test"
version = "0.0.0"
edition = "2024"
license.workspace = true
publish = false

[dependencies]
proptest.workspace = true
sumi-format = { path = "../format" }
sumi-frontend = { path = "../frontend" }
sumi-hir = { path = "../hir" }
sumi-lexer = { path = "../lexer" }
sumi-syntax = { path = "../syntax" }
sumi-text = { path = "../text" }

[dev-dependencies]
tempfile.workspace = true
