[package]
name = "sumi-frontend"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
sumi-diagnostics = { path = "../diagnostics" }
sumi-lexer = { path = "../lexer" }
sumi-syntax = { path = "../syntax" }
sumi-text = { path = "../text" }

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
sumi-format = { path = "../format" }
sumi-test = { path = "../test" }
tempfile.workspace = true

[[bench]]
name = "pipeline"
path = "benches/pipeline/main.rs"
harness = false
