//! The generated files, each rendered from a [`Grammar`]: the lexer's token
//! vocabulary, the parser's grammar vocabulary, and the reference chapter.
//!
//! Each file is one template. Its dynamic parts — enum variants, match arms,
//! tables — are rendered first and spliced in; rustfmt settles the layout of
//! the Rust ones afterwards, so their templates only need to be readable.

use std::io::Write as _;
use std::process::{Command, Stdio};

use crate::grammar::{
    BINARY_OPERATOR_RULE, Binary, ERROR_NODE, Grammar, PREFIX_OPERATOR_RULE, Shape, Token,
    binding_power,
};

const GENERATED: &str = "@generated by `cargo xtask codegen` from `sumi.grammar`; do not edit.";

/// Format generated Rust the way `cargo fmt` would, so the checked-in file
/// passes the format check untouched.
pub fn rustfmt(source: &str) -> Result<String, String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| format!("running rustfmt: {error} (install the rustfmt component)"))?;
    child
        .stdin
        .take()
        .expect("stdin is piped")
        .write_all(source.as_bytes())
        .map_err(|error| format!("feeding rustfmt: {error}"))?;
    let output = child
        .wait_with_output()
        .map_err(|error| format!("waiting for rustfmt: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "rustfmt rejected the generated code:\n{}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    String::from_utf8(output.stdout).map_err(|error| error.to_string())
}

/// `crates/lexer/src/kind.rs`.
pub fn lexer_kind(grammar: &Grammar) -> String {
    let tokens = &grammar.tokens;
    let shaped = |shape| tokens.iter().filter(move |token| token.shape == shape);
    let variants = variants(
        tokens
            .iter()
            .map(|token| (docs(&token.doc), token.name.clone())),
    );
    let all = list(
        tokens.iter().map(|token| format!("Self::{}", token.name)),
        ", ",
    );
    let keywords = arms(shaped(Shape::Keyword).map(|token| {
        (
            format!("{:?}", text(token)),
            format!("Self::{}", token.name),
        )
    }));
    let puncts = arms(shaped(Shape::Punct).map(|token| {
        let byte = text(token)
            .chars()
            .next()
            .expect("one character")
            .escape_default();
        (format!("b'{byte}'"), format!("Self::{}", token.name))
    }));
    let texts = arms(
        tokens
            .iter()
            .filter(|token| token.text.is_some())
            .map(|token| {
                (
                    format!("Self::{}", token.name),
                    format!("{:?}", text(token)),
                )
            }),
    );
    let trivia = matches_any(
        "self",
        shaped(Shape::Trivia).map(|token| format!("Self::{}", token.name)),
    );
    let descriptions = arms(tokens.iter().map(|token| {
        (
            format!("Self::{}", token.name),
            format!("{:?}", token.description),
        )
    }));
    format!(
        r#"//! The token vocabulary: every kind the lexer assigns, the keyword and
//! punctuation tables it classifies by, and the fixed text and diagnostic
//! description of each kind.
//!
//! {GENERATED}

/// The language-level kind of a token.
///
/// The lexer assigns these while a token's bytes are cache-hot; the
/// shape-only [`RawKind`](crate::RawKind) is stored beside them for phases
/// that reason about lexical shape. Every kind occupies a source range:
/// there is deliberately no EOF sentinel (end of input is the end of the
/// token buffer, surfaced as `Option` by lookahead APIs), and compound
/// operators are not kinds: the parser glues them from adjacent
/// punctuation.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum SyntaxKind {{
{variants}}}

impl SyntaxKind {{
    /// Every kind, in declaration order.
    pub const ALL: [Self; {count}] = [{all}];

    /// The keyword kind for `text`, if it is a reserved word.
    pub fn from_keyword(text: &str) -> Option<Self> {{
        Some(match text {{
{keywords}            _ => return None,
        }})
    }}

    /// The kind for a punctuation character, if it has a role in the
    /// language. Punctuation without one has no kind and lexes as an error
    /// token.
    pub fn from_punct(byte: u8) -> Option<Self> {{
        Some(match byte {{
{puncts}            _ => return None,
        }})
    }}

    /// The fixed text of a keyword or punctuation kind; `None` for kinds
    /// whose text varies.
    pub fn text(self) -> Option<&'static str> {{
        Some(match self {{
{texts}            _ => return None,
        }})
    }}

    /// Whether the kind is trivia — whitespace, line breaks, and comments —
    /// which the grammar never sees.
    pub fn is_trivia(self) -> bool {{
        {trivia}
    }}

    /// How the kind reads as the object of "expected" in a diagnostic.
    pub fn describe(self) -> &'static str {{
        match self {{
{descriptions}        }}
    }}
}}
"#,
        count = tokens.len(),
    )
}

/// `crates/syntax/src/kind.rs`.
pub fn syntax_kind(grammar: &Grammar) -> String {
    let class = |member: fn(&Token) -> bool| {
        matches_any(
            "kind",
            grammar
                .tokens
                .iter()
                .filter(|token| member(token))
                .map(kind),
        )
    };
    let nodes = variants(
        grammar
            .nodes()
            .map(|rule| (docs(&rule.doc), rule.name.clone())),
    );
    let starts_expression = class(|token| token.flags.expr);
    let introduces_statement = class(|token| token.flags.stmt);
    let can_end_statement = class(|token| token.flags.end);
    let starts_item = class(|token| token.flags.item);
    let is_prefix_operator = matches_any(
        "kind",
        grammar
            .prefix
            .iter()
            .map(|text| kind(first_token(grammar, text))),
    );
    let (continuation_glued, continuation) = continuation_arms(grammar);
    let pairs = list(
        grammar
            .pairs
            .iter()
            .map(|pair| format!("(SyntaxKind::{}, SyntaxKind::{})", pair.opener, pair.closer)),
        ", ",
    );
    let closers = arms(grammar.pairs.iter().map(|pair| {
        (
            format!("SyntaxKind::{}", pair.opener),
            format!("SyntaxKind::{}", pair.closer),
        )
    }));
    let openers = arms(grammar.pairs.iter().map(|pair| {
        (
            format!("SyntaxKind::{}", pair.closer),
            format!("SyntaxKind::{}", pair.opener),
        )
    }));
    let prefix_bp = grammar.prefix_binding_power();
    let operators = variants(
        grammar
            .binary
            .iter()
            .map(|op| (format!("/// `{}`\n", op.text), op.name.clone())),
    );
    let mut levels: Vec<u8> = Vec::new();
    for op in &grammar.binary {
        if !levels.contains(&op.level) {
            levels.push(op.level);
        }
    }
    let binding_powers = arms(levels.into_iter().map(|level| {
        let ops = grammar.binary.iter().filter(|op| op.level == level);
        let pattern = list(ops.map(|op| format!("Self::{}", op.name)), " | ");
        let (left, right) = binding_power(level);
        (pattern, format!("({left}, {right})"))
    }));
    let comparisons = matches_any(
        "self",
        grammar
            .binary
            .iter()
            .filter(|op| op.comparison)
            .map(|op| format!("Self::{}", op.name)),
    );
    let (operator_glued, operator_arms) = binary_operator_arms(grammar);
    format!(
        r#"//! The grammar's vocabulary: node kinds, and the token classes, bracket
//! pairs, and operator tables the parser and the newline rule read.
//!
//! {GENERATED}

/// The language-level kind of a token, assigned by the fused lexer and
/// re-exported here where the grammar consumes it.
///
/// Kept separate from the tree's [`NodeKind`]: nodes cover ranges of
/// tokens rather than sitting among them, so the two vocabularies never
/// share a slot.
pub use sumi_lexer::SyntaxKind;

/// The kind of a syntax tree node.
///
/// A node is structure only, so this vocabulary is disjoint from
/// [`SyntaxKind`]: a tree slot never holds a token kind, and a token
/// buffer slot never holds a node kind.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum NodeKind {{
{nodes}    /// Covers tokens the parser could not parse.
    {ERROR_NODE},
}}

/// Whether a token of this kind can begin an expression.
pub fn starts_expression(kind: SyntaxKind) -> bool {{
    {starts_expression}
}}

/// Whether a token of this kind begins a statement that is not an
/// expression: a declaration keyword, `_`, or an `Error` run.
pub fn introduces_statement(kind: SyntaxKind) -> bool {{
    {introduces_statement}
}}

/// Whether a token of this kind can begin a statement.
pub fn starts_statement(kind: SyntaxKind) -> bool {{
    introduces_statement(kind) || starts_expression(kind)
}}

/// Whether a statement can end after a token of this kind: values and
/// closers can; operators, openers, and introducer keywords need more.
pub fn can_end_statement(kind: SyntaxKind) -> bool {{
    {can_end_statement}
}}

/// Whether a token of this kind begins a top-level item.
pub fn starts_item(kind: SyntaxKind) -> bool {{
    {starts_item}
}}

/// Whether a token of this kind is a prefix operator.
pub fn is_prefix_operator(kind: SyntaxKind) -> bool {{
    {is_prefix_operator}
}}

/// Whether a token of this kind continues a statement left open on the
/// previous line; `glued` is the kind of the token glued after it, if
/// any.
///
/// Continuation tokens can never start a statement: the keywords declared
/// to continue, and the binary operators — a compound one only when glued
/// into shape, and one that is also a prefix operator only when spaced
/// from what follows, since glued it opens an operand instead.
pub fn continues_statement(kind: SyntaxKind, {continuation_glued}: Option<SyntaxKind>) -> bool {{
    match kind {{
{continuation}        _ => false,
    }}
}}

/// The bracket pairs the token stream matches, opener then closer.
pub const BRACKET_PAIRS: [(SyntaxKind, SyntaxKind); {pair_count}] = [{pairs}];

/// The closer pairing with an opener of this kind.
pub fn closer(opener: SyntaxKind) -> Option<SyntaxKind> {{
    Some(match opener {{
{closers}        _ => return None,
    }})
}}

/// The opener pairing with a closer of this kind.
pub fn opener(closer: SyntaxKind) -> Option<SyntaxKind> {{
    Some(match closer {{
{openers}        _ => return None,
    }})
}}

/// Whether a token of this kind opens a bracket pair.
pub fn is_opener(kind: SyntaxKind) -> bool {{
    closer(kind).is_some()
}}

/// Whether a token of this kind closes a bracket pair.
pub fn is_closer(kind: SyntaxKind) -> bool {{
    opener(kind).is_some()
}}

/// Whether a token of this kind opens or closes a bracket pair.
pub fn is_bracket(kind: SyntaxKind) -> bool {{
    is_opener(kind) || is_closer(kind)
}}

/// The binding power of a prefix operator's operand: tighter than every
/// binary operator, so only a call binds closer.
pub const PREFIX_BP: u8 = {prefix_bp};

/// A binary operator.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BinaryOp {{
{operators}}}

impl BinaryOp {{
    /// Left and right binding powers. Every operator associates left, so
    /// it binds tighter on the right; comparisons too, so a chain parses
    /// left to right and is then rejected.
    pub fn binding_power(self) -> (u8, u8) {{
        match self {{
{binding_powers}        }}
    }}

    /// Whether the operator is a comparison, which does not chain.
    pub fn is_comparison(self) -> bool {{
        {comparisons}
    }}
}}

/// The binary operator a token of kind `first` begins, and its width in
/// tokens; `glued` is the kind of the token glued after it, if any. A
/// compound operator is its tokens glued; a lone `=` is no operator.
pub fn binary_operator(first: SyntaxKind, {operator_glued}: Option<SyntaxKind>) -> Option<(BinaryOp, usize)> {{
    Some(match first {{
{operator_arms}        _ => return None,
    }})
}}
"#,
        pair_count = grammar.pairs.len(),
    )
}

/// The arms of `continues_statement`, and the name of its `glued`
/// parameter — underscored when no arm reads it.
///
/// Continuation is derived: a token continues when it is declared to, or
/// when a binary operator begins with it — a compound one only when glued
/// into shape, and one that is also a prefix operator only when spaced
/// from what follows.
fn continuation_arms(grammar: &Grammar) -> (&'static str, String) {
    let mut arms: Vec<(String, Vec<String>)> = Vec::new();
    for token in &grammar.tokens {
        let condition = if token.flags.continues {
            "true".to_owned()
        } else {
            let (singles, compounds): (Vec<_>, Vec<_>) = grammar
                .binary
                .iter()
                .map(|op| operator_tokens(grammar, &op.text))
                .filter(|tokens| tokens[0].name == token.name)
                .partition(|tokens| tokens.len() == 1);
            if singles.is_empty() && compounds.is_empty() {
                continue;
            }
            let prefix = grammar
                .prefix
                .iter()
                .any(|text| first_token(grammar, text).name == token.name);
            let mut parts = Vec::new();
            if !singles.is_empty() {
                parts.push(if prefix { "glued.is_none()" } else { "true" }.to_owned());
            }
            if !compounds.is_empty() && parts.first().map(String::as_str) != Some("true") {
                let seconds = compounds
                    .iter()
                    .map(|tokens| format!("Some({})", kind(tokens[1])));
                parts.push(format!("matches!(glued, {})", list(seconds, " | ")));
            }
            parts.join(" || ")
        };
        match arms.iter_mut().find(|(known, _)| *known == condition) {
            Some((_, kinds)) => kinds.push(kind(token)),
            None => arms.push((condition, vec![kind(token)])),
        }
    }
    let glued = if arms
        .iter()
        .any(|(condition, _)| condition.contains("glued"))
    {
        "glued"
    } else {
        "_glued"
    };
    let arms = arms
        .into_iter()
        .map(|(condition, kinds)| (kinds.join(" | "), condition));
    (glued, self::arms(arms))
}

/// The arms of `binary_operator`, compound operators first so a glued
/// second token is matched before the single-token operator it extends,
/// and the name of its `glued` parameter.
fn binary_operator_arms(grammar: &Grammar) -> (&'static str, String) {
    let operators: Vec<(&Binary, Vec<&Token>)> = grammar
        .binary
        .iter()
        .map(|op| (op, operator_tokens(grammar, &op.text)))
        .collect();
    let compound = |(_, tokens): &&(&Binary, Vec<&Token>)| tokens.len() == 2;
    let glued = if operators.iter().any(|entry| compound(&entry)) {
        "glued"
    } else {
        "_glued"
    };
    let compounds = operators.iter().filter(compound).map(|(op, tokens)| {
        (
            format!("{} if glued == Some({})", kind(tokens[0]), kind(tokens[1])),
            format!("(BinaryOp::{}, 2)", op.name),
        )
    });
    let singles = operators
        .iter()
        .filter(|entry| !compound(entry))
        .map(|(op, tokens)| (kind(tokens[0]), format!("(BinaryOp::{}, 1)", op.name)));
    (glued, arms(compounds.chain(singles)))
}

/// `docs/reference/grammar.md`.
pub fn reference(grammar: &Grammar) -> String {
    let shapes = [
        (Shape::Trivia, "Trivia"),
        (Shape::Ident, "Names"),
        (Shape::Keyword, "Keywords"),
        (Shape::Literal, "Literals"),
        (Shape::Punct, "Punctuation"),
        (Shape::Error, "Errors"),
    ];
    let mut tokens = String::new();
    for (shape, heading) in shapes {
        let texted = matches!(shape, Shape::Keyword | Shape::Punct);
        let header = if texted {
            ["Text", "Kind", "Classes", "Notes"]
        } else {
            ["Kind", "Reads as", "Classes", "Notes"]
        };
        let rows: Vec<Vec<String>> = grammar
            .tokens
            .iter()
            .filter(|token| token.shape == shape)
            .map(|token| {
                let (first, second) = if texted {
                    (code(text(token)), code(&token.name))
                } else {
                    (code(&token.name), cell(&token.description))
                };
                vec![first, second, classes(token), cell(&token.doc.join(" "))]
            })
            .collect();
        if !rows.is_empty() {
            tokens += &format!("### {heading}\n\n{}\n", table(&header, rows));
        }
    }
    let compounds = bullets(grammar.compounds.iter().map(|text| code(text)));
    let pairs = bullets(grammar.pairs.iter().map(|pair| {
        let bracket = |name: &str| code(text(grammar.token(name).expect("validated")));
        format!("{} … {}", bracket(&pair.opener), bracket(&pair.closer))
    }));
    let prefix = bullets(grammar.prefix.iter().map(|text| code(text)));
    let mut levels: Vec<u8> = grammar.binary.iter().map(|op| op.level).collect();
    levels.sort_unstable_by(|a, b| b.cmp(a));
    levels.dedup();
    let binary = table(
        &["Level", "Operators", "Notes"],
        levels.into_iter().map(|level| {
            let ops: Vec<&Binary> = grammar
                .binary
                .iter()
                .filter(|op| op.level == level)
                .collect();
            let notes = match ops.iter().filter(|op| op.comparison).count() {
                0 => "",
                n if n == ops.len() => "comparison",
                _ => "partly comparison",
            };
            let texts = list(ops.iter().map(|op| code(&op.text)), " ");
            vec![level.to_string(), texts, notes.to_owned()]
        }),
    );
    let name = |token: &Token| code(token.text.as_deref().unwrap_or(&token.name));
    let class = |member: fn(&Token) -> bool| {
        list(
            grammar
                .tokens
                .iter()
                .filter(|token| member(token))
                .map(name),
            ", ",
        )
    };
    let expr = class(|token| token.flags.expr);
    let stmt = class(|token| token.flags.stmt);
    let end = class(|token| token.flags.end);
    let item = class(|token| token.flags.item);
    let continues = class(|token| token.flags.continues);
    let spaced = list(
        grammar
            .prefix
            .iter()
            .filter(|text| grammar.binary.iter().any(|op| op.text == **text))
            .map(|text| code(text)),
        ", ",
    );
    let rules: String = grammar
        .rules
        .iter()
        .map(|rule| {
            let doc: String = rule.doc.iter().map(|line| format!("// {line}\n")).collect();
            format!("{doc}{} = {}\n", rule.name, rule.body)
        })
        .collect();
    let prefix_rule = list(grammar.prefix.iter().map(|text| format!("'{text}'")), " | ");
    let binary_rule = list(
        grammar.binary.iter().map(|op| format!("'{}'", op.text)),
        " | ",
    );
    format!(
        "# Grammar

<!-- {GENERATED} -->

Generated from [`sumi.grammar`](../../sumi.grammar), the one declaration of
Sumi's tokens, syntax nodes, and the token classes the lexer, the newline
rule, and the parser derive from them. Edit that file and run
`cargo xtask codegen`: this chapter, the kind enums, and every derived
table follow.

## Tokens

Trivia never reaches the grammar; every other kind is a significant token.
*Reads as* is how a kind is named after \"expected\" in a diagnostic. The
*classes* are the flags declared in the grammar: `expr` can begin an
expression, `stmt` begins a statement that is not an expression, `end` lets
a statement end after it, `item` begins a top-level item, and `continue`
continues the previous line. Operators take their classes from the
[operator tables](#operators) instead.

{tokens}### Compound operators

The lexer produces single punctuation only. The parser glues these from
adjacent characters; a space between them keeps them apart.

{compounds}
## Brackets

The token stream pairs each closer with the nearest open bracket of its
kind, discarding unmatched openers above that match; an orphan closer
pairs with nothing. Grammar decides whether a pair is meaningful where it
appears.

{pairs}
## Operators

### Prefix

A prefix operator is glued to its operand, which binds tighter than any
binary operator: only a call binds closer.

{prefix}
### Binary

Every binary operator associates left and must be spaced on both sides.
Higher levels bind tighter. Comparisons do not chain: `a < b < c` is
rejected rather than parsed.

{binary}
## Lines

Sumi has no `;`. A line break ends a statement when the token before it can
end one, the token after it does not continue one, and no parenthesis the
stream closes is open around it. These classes decide the first two;
the parser's spacing rules keep the third unambiguous.

- **Can begin an expression:** {expr}.
- **Begin a statement without being an expression:** {stmt}.
- **A statement can end after:** {end}.
- **Begin a top-level item:** {item}.
- **Continue the previous line:** {continues}, and any binary operator leading the line — a compound one when glued into shape, and {spaced} only when spaced from what follows, since glued it opens an operand.

## Syntax nodes

The shape of valid syntax, in ungrammar notation: `'text'` is a token by
its text, a capitalized name is a node kind, a token kind, or a category,
`?` is optional, `*` repeats, and `|` separates alternatives. A rule that
only lists other rules is a category, not a node kind. The tree is
error-tolerant: any part of a node may be missing, and an `{ERROR_NODE}`
node covering tokens the parser could not parse may appear anywhere.

```
{rules}
// Defined by the operator tables.
{PREFIX_OPERATOR_RULE} = {prefix_rule}
{BINARY_OPERATOR_RULE} = {binary_rule}
```
"
    )
}

/// A `///` comment per line, ready to precede an item.
fn docs(lines: &[String]) -> String {
    lines
        .iter()
        .map(|line| {
            if line.is_empty() {
                "///\n".to_owned()
            } else {
                format!("/// {line}\n")
            }
        })
        .collect()
}

/// Enum variants from `(rendered docs, name)` pairs.
fn variants(items: impl Iterator<Item = (String, String)>) -> String {
    items.map(|(doc, name)| format!("{doc}{name},\n")).collect()
}

/// Match arms from `(pattern, value)` pairs.
fn arms(items: impl Iterator<Item = (String, String)>) -> String {
    items
        .map(|(pattern, value)| format!("{pattern} => {value},\n"))
        .collect()
}

/// A `matches!` over the patterns, or `false` when there are none.
fn matches_any(subject: &str, patterns: impl Iterator<Item = String>) -> String {
    let patterns = list(patterns, " | ");
    if patterns.is_empty() {
        "false".to_owned()
    } else {
        format!("matches!({subject}, {patterns})")
    }
}

fn list(items: impl Iterator<Item = String>, separator: &str) -> String {
    items.collect::<Vec<_>>().join(separator)
}

fn text(token: &Token) -> &str {
    token
        .text
        .as_deref()
        .expect("a keyword or punctuation token has text")
}

fn kind(token: &Token) -> String {
    format!("SyntaxKind::{}", token.name)
}

fn operator_tokens<'a>(grammar: &'a Grammar, text: &str) -> Vec<&'a Token> {
    grammar.operator_tokens(text).expect("validated")
}

fn first_token<'a>(grammar: &'a Grammar, text: &str) -> &'a Token {
    operator_tokens(grammar, text)[0]
}

/// The token's flags as Markdown, in grammar-file spelling.
fn classes(token: &Token) -> String {
    let flags = token.flags;
    let set = [
        (flags.expr, "expr"),
        (flags.stmt, "stmt"),
        (flags.end, "end"),
        (flags.item, "item"),
        (flags.continues, "continue"),
    ];
    list(
        set.into_iter()
            .filter(|(set, _)| *set)
            .map(|(_, name)| code(name)),
        " ",
    )
}

fn bullets(items: impl Iterator<Item = String>) -> String {
    items.map(|item| format!("- {item}\n")).collect()
}

/// A Markdown table.
fn table(header: &[&str], rows: impl IntoIterator<Item = Vec<String>>) -> String {
    let row = |cells: Vec<String>| format!("| {} |\n", cells.join(" | "));
    let mut out = row(header.iter().map(|&cell| cell.to_owned()).collect());
    out += &row(vec!["---".to_owned(); header.len()]);
    rows.into_iter().map(row).for_each(|line| out += &line);
    out
}

/// Text inside a Markdown table cell.
fn cell(text: &str) -> String {
    text.replace('|', "\\|")
}

/// A Markdown code span, safe inside a table cell.
fn code(text: &str) -> String {
    format!("`{}`", cell(text))
}
