//! The generated files, each rendered from a [`Grammar`]: the lexer's token
//! vocabulary, the parser's grammar vocabulary, and the reference chapter.
//!
//! Each file is one template. Its dynamic parts — enum variants, match arms,
//! tables — are rendered first and spliced in; rustfmt settles the layout of
//! the Rust ones afterwards, so their templates only need to be readable.

use std::io::Write as _;
use std::process::{Command, Stdio};

use crate::grammar::{
    BINARY_OPERATOR_RULE, Binary, ERROR_NODE, Field, FieldType, Grammar, PREFIX_OPERATOR_RULE,
    Rule, Shape, Token, alternatives, binding_power,
};

const GENERATED: &str = "@generated by `cargo xtask codegen` from `sumi.grammar`; do not edit.";

/// Format generated Rust the way `cargo fmt` would, so the checked-in file
/// passes the format check untouched.
pub fn rustfmt(source: &str) -> Result<String, String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| format!("running rustfmt: {error} (install the rustfmt component)"))?;
    child
        .stdin
        .take()
        .expect("stdin is piped")
        .write_all(source.as_bytes())
        .map_err(|error| format!("feeding rustfmt: {error}"))?;
    let output = child
        .wait_with_output()
        .map_err(|error| format!("waiting for rustfmt: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "rustfmt rejected the generated code:\n{}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    String::from_utf8(output.stdout).map_err(|error| error.to_string())
}

/// `crates/lexer/src/generated/mod.rs`.
pub fn lexer_kind(grammar: &Grammar) -> String {
    let tokens = &grammar.tokens;
    let shaped = |shape| tokens.iter().filter(move |token| token.shape == shape);
    let variants = variants(
        tokens
            .iter()
            .map(|token| (docs(&token.doc), token.name.clone())),
    );
    let all = list(
        tokens.iter().map(|token| format!("Self::{}", token.name)),
        ", ",
    );
    let keywords = arms(shaped(Shape::Keyword).map(|token| {
        (
            format!("{:?}", text(token)),
            format!("Self::{}", token.name),
        )
    }));
    let puncts = arms(shaped(Shape::Punct).map(|token| {
        let byte = text(token)
            .chars()
            .next()
            .expect("one character")
            .escape_default();
        (format!("b'{byte}'"), format!("Self::{}", token.name))
    }));
    let texts = arms(
        tokens
            .iter()
            .filter(|token| token.text.is_some())
            .map(|token| {
                (
                    format!("Self::{}", token.name),
                    format!("{:?}", text(token)),
                )
            }),
    );
    let trivia = matches_any(
        "self",
        shaped(Shape::Trivia).map(|token| format!("Self::{}", token.name)),
    );
    let descriptions = arms(tokens.iter().map(|token| {
        (
            format!("Self::{}", token.name),
            format!("{:?}", token.description),
        )
    }));
    format!(
        r#"//! The token vocabulary: every kind the lexer assigns, the keyword and
//! punctuation tables it classifies by, and the fixed text and diagnostic
//! description of each kind.
//!
//! {GENERATED}

/// The language-level kind of a token.
///
/// The lexer assigns these while a token's bytes are cache-hot; the
/// shape-only [`RawKind`](crate::RawKind) is stored beside them for phases
/// that reason about lexical shape. Every kind occupies a source range:
/// there is deliberately no EOF sentinel (end of input is the end of the
/// token buffer, surfaced as `Option` by lookahead APIs), and compound
/// operators are not kinds: the parser glues them from adjacent
/// punctuation.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum SyntaxKind {{
{variants}}}

impl SyntaxKind {{
    /// Every kind, in declaration order.
    pub const ALL: [Self; {count}] = [{all}];

    /// The keyword kind for `text`, if it is a reserved word.
    pub fn from_keyword(text: &str) -> Option<Self> {{
        Some(match text {{
{keywords}            _ => return None,
        }})
    }}

    /// The kind for a punctuation character, if it has a role in the
    /// language. Punctuation without one has no kind and lexes as an error
    /// token.
    #[inline(always)]
    pub fn from_punct(byte: u8) -> Option<Self> {{
        Some(match byte {{
{puncts}            _ => return None,
        }})
    }}

    /// The fixed text of a keyword or punctuation kind; `None` for kinds
    /// whose text varies.
    pub fn text(self) -> Option<&'static str> {{
        Some(match self {{
{texts}            _ => return None,
        }})
    }}

    /// Whether the kind is trivia — whitespace, line breaks, and comments —
    /// which the grammar never sees.
    pub fn is_trivia(self) -> bool {{
        {trivia}
    }}

    /// How the kind reads as the object of "expected" in a diagnostic.
    pub fn describe(self) -> &'static str {{
        match self {{
{descriptions}        }}
    }}
}}
"#,
        count = tokens.len(),
    )
}

/// `crates/syntax/src/generated/mod.rs`.
pub fn syntax_kind(grammar: &Grammar) -> String {
    let class = |member: fn(&Token) -> bool| {
        matches_any(
            "kind",
            grammar
                .tokens
                .iter()
                .filter(|token| member(token))
                .map(kind),
        )
    };
    let nodes = variants(
        grammar
            .nodes()
            .map(|rule| (docs(&rule.doc), rule.name.clone())),
    );
    let starts_expression = class(|token| token.flags.expr);
    let introduces_statement = class(|token| token.flags.stmt);
    let can_end_statement = class(|token| token.flags.end);
    let starts_item = class(|token| token.flags.item);
    let is_prefix_operator = matches_any(
        "kind",
        grammar
            .prefix
            .iter()
            .map(|text| kind(first_token(grammar, text))),
    );
    let (continuation_glued, continuation) = continuation_arms(grammar);
    let pairs = list(
        grammar
            .pairs
            .iter()
            .map(|pair| format!("(SyntaxKind::{}, SyntaxKind::{})", pair.opener, pair.closer)),
        ", ",
    );
    let closers = arms(grammar.pairs.iter().map(|pair| {
        (
            format!("SyntaxKind::{}", pair.opener),
            format!("SyntaxKind::{}", pair.closer),
        )
    }));
    let openers = arms(grammar.pairs.iter().map(|pair| {
        (
            format!("SyntaxKind::{}", pair.closer),
            format!("SyntaxKind::{}", pair.opener),
        )
    }));
    let pair_indices = arms(grammar.pairs.iter().enumerate().map(|(index, pair)| {
        (
            format!("SyntaxKind::{} | SyntaxKind::{}", pair.opener, pair.closer),
            index.to_string(),
        )
    }));
    let statement_openers = grammar
        .pairs
        .iter()
        .filter(|pair| pair.statements)
        .map(|pair| format!("SyntaxKind::{}", pair.opener))
        .collect::<Vec<_>>();
    let encloses_statements = if statement_openers.is_empty() {
        "false".to_owned()
    } else {
        format!("matches!(opener, {})", statement_openers.join(" | "))
    };
    let prefix_bp = grammar.prefix_binding_power();
    let operators = variants(
        grammar
            .binary
            .iter()
            .map(|op| (format!("/// `{}`\n", op.text), op.name.clone())),
    );
    let mut levels: Vec<u8> = Vec::new();
    for op in &grammar.binary {
        if !levels.contains(&op.level) {
            levels.push(op.level);
        }
    }
    let binding_powers = arms(levels.into_iter().map(|level| {
        let ops = grammar.binary.iter().filter(|op| op.level == level);
        let pattern = list(ops.map(|op| format!("Self::{}", op.name)), " | ");
        let (left, right) = binding_power(level);
        (pattern, format!("({left}, {right})"))
    }));
    let comparisons = matches_any(
        "self",
        grammar
            .binary
            .iter()
            .filter(|op| op.comparison)
            .map(|op| format!("Self::{}", op.name)),
    );
    let (operator_glued, operator_arms) = binary_operator_arms(grammar);
    format!(
        r#"//! The grammar's vocabulary: node kinds, and the token classes, bracket
//! pairs, and operator tables the parser and the newline rule read.
//!
//! {GENERATED}

/// The language-level kind of a token, assigned by the fused lexer and
/// re-exported here where the grammar consumes it.
///
/// Kept separate from the tree's [`NodeKind`]: nodes cover ranges of
/// tokens rather than sitting among them, so the two vocabularies never
/// share a slot.
pub use sumi_lexer::SyntaxKind;

/// The typed views over the tree, generated beside this module.
pub mod ast;

/// The kind of a syntax tree node.
///
/// A node is structure only, so this vocabulary is disjoint from
/// [`SyntaxKind`]: a tree slot never holds a token kind, and a token
/// buffer slot never holds a node kind.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum NodeKind {{
{nodes}    /// Covers tokens the parser could not parse.
    {ERROR_NODE},
}}

/// Whether a token of this kind can begin an expression.
pub fn starts_expression(kind: SyntaxKind) -> bool {{
    {starts_expression}
}}

/// Whether a token of this kind begins a statement that is not an
/// expression: a declaration keyword, `_`, or an `Error` run.
pub fn introduces_statement(kind: SyntaxKind) -> bool {{
    {introduces_statement}
}}

/// Whether a token of this kind can begin a statement.
pub fn starts_statement(kind: SyntaxKind) -> bool {{
    introduces_statement(kind) || starts_expression(kind)
}}

/// Whether a statement can end after a token of this kind: values and
/// closers can; operators, openers, and introducer keywords need more.
pub fn can_end_statement(kind: SyntaxKind) -> bool {{
    {can_end_statement}
}}

/// Whether a token of this kind begins a top-level item.
pub fn starts_item(kind: SyntaxKind) -> bool {{
    {starts_item}
}}

/// Whether a token of this kind is a prefix operator.
pub fn is_prefix_operator(kind: SyntaxKind) -> bool {{
    {is_prefix_operator}
}}

/// Whether a token of this kind continues a statement left open on the
/// previous line; `glued` is the kind of the token glued after it, if
/// any.
///
/// Continuation tokens can never start a statement: the keywords declared
/// to continue, and the binary operators — a compound one only when glued
/// into shape, and one that is also a prefix operator only when spaced
/// from what follows, since glued it opens an operand instead.
pub fn continues_statement(kind: SyntaxKind, {continuation_glued}: Option<SyntaxKind>) -> bool {{
    match kind {{
{continuation}        _ => false,
    }}
}}

/// The bracket pairs the token stream matches, opener then closer.
pub const BRACKET_PAIRS: [(SyntaxKind, SyntaxKind); {pair_count}] = [{pairs}];

/// The index in [`BRACKET_PAIRS`] of the pair a token of this kind opens
/// or closes: a match, so no table is read.
pub fn pair_index(kind: SyntaxKind) -> Option<usize> {{
    Some(match kind {{
{pair_indices}        _ => return None,
    }})
}}

/// The closer pairing with an opener of this kind.
pub fn closer(opener: SyntaxKind) -> Option<SyntaxKind> {{
    Some(match opener {{
{closers}        _ => return None,
    }})
}}

/// The opener pairing with a closer of this kind.
pub fn opener(closer: SyntaxKind) -> Option<SyntaxKind> {{
    Some(match closer {{
{openers}        _ => return None,
    }})
}}

/// Whether a token of this kind opens a bracket pair.
pub fn is_opener(kind: SyntaxKind) -> bool {{
    closer(kind).is_some()
}}

/// Whether a token of this kind closes a bracket pair.
pub fn is_closer(kind: SyntaxKind) -> bool {{
    opener(kind).is_some()
}}

/// Whether a token of this kind opens or closes a bracket pair.
pub fn is_bracket(kind: SyntaxKind) -> bool {{
    is_opener(kind) || is_closer(kind)
}}

/// Whether the pair opened by this kind encloses statements, so that line
/// breaks inside it end statements as a block's do. Every other pair
/// suspends the newline rule between its brackets.
pub fn encloses_statements(opener: SyntaxKind) -> bool {{
    {encloses_statements}
}}

/// The binding power of a prefix operator's operand: tighter than every
/// binary operator, so only a call binds closer.
pub const PREFIX_BP: u8 = {prefix_bp};

/// A binary operator.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BinaryOp {{
{operators}}}

impl BinaryOp {{
    /// Left and right binding powers. Every operator associates left, so
    /// it binds tighter on the right; comparisons too, so a chain parses
    /// left to right and is then rejected.
    pub fn binding_power(self) -> (u8, u8) {{
        match self {{
{binding_powers}        }}
    }}

    /// Whether the operator is a comparison, which does not chain.
    pub fn is_comparison(self) -> bool {{
        {comparisons}
    }}
}}

/// The binary operator a token of kind `first` begins, and its width in
/// tokens; `glued` is the kind of the token glued after it, if any. A
/// compound operator is its tokens glued; a lone `=` is no operator.
pub fn binary_operator(first: SyntaxKind, {operator_glued}: Option<SyntaxKind>) -> Option<(BinaryOp, usize)> {{
    Some(match first {{
{operator_arms}        _ => return None,
    }})
}}
"#,
        pair_count = grammar.pairs.len(),
        pair_indices = pair_indices,
    )
}

/// The arms of `continues_statement`, and the name of its `glued`
/// parameter — underscored when no arm reads it.
///
/// Continuation is derived: a token continues when it is declared to, or
/// when a binary operator begins with it — a compound one only when glued
/// into shape, and one that is also a prefix operator only when spaced
/// from what follows.
fn continuation_arms(grammar: &Grammar) -> (&'static str, String) {
    let mut arms: Vec<(String, Vec<String>)> = Vec::new();
    for token in &grammar.tokens {
        let condition = if token.flags.continues {
            "true".to_owned()
        } else {
            let (singles, compounds): (Vec<_>, Vec<_>) = grammar
                .binary
                .iter()
                .map(|op| operator_tokens(grammar, &op.text))
                .filter(|tokens| tokens[0].name == token.name)
                .partition(|tokens| tokens.len() == 1);
            if singles.is_empty() && compounds.is_empty() {
                continue;
            }
            let prefix = grammar
                .prefix
                .iter()
                .any(|text| first_token(grammar, text).name == token.name);
            let mut parts = Vec::new();
            if !singles.is_empty() {
                parts.push(if prefix { "glued.is_none()" } else { "true" }.to_owned());
            }
            if !compounds.is_empty() && parts.first().map(String::as_str) != Some("true") {
                let seconds = compounds
                    .iter()
                    .map(|tokens| format!("Some({})", kind(tokens[1])));
                parts.push(format!("matches!(glued, {})", list(seconds, " | ")));
            }
            parts.join(" || ")
        };
        match arms.iter_mut().find(|(known, _)| *known == condition) {
            Some((_, kinds)) => kinds.push(kind(token)),
            None => arms.push((condition, vec![kind(token)])),
        }
    }
    let glued = if arms
        .iter()
        .any(|(condition, _)| condition.contains("glued"))
    {
        "glued"
    } else {
        "_glued"
    };
    let arms = arms
        .into_iter()
        .map(|(condition, kinds)| (kinds.join(" | "), condition));
    (glued, self::arms(arms))
}

/// The arms of `binary_operator`, compound operators first so a glued
/// second token is matched before the single-token operator it extends,
/// and the name of its `glued` parameter.
fn binary_operator_arms(grammar: &Grammar) -> (&'static str, String) {
    let operators: Vec<(&Binary, Vec<&Token>)> = grammar
        .binary
        .iter()
        .map(|op| (op, operator_tokens(grammar, &op.text)))
        .collect();
    let compound = |(_, tokens): &&(&Binary, Vec<&Token>)| tokens.len() == 2;
    let glued = if operators.iter().any(|entry| compound(&entry)) {
        "glued"
    } else {
        "_glued"
    };
    let compounds = operators.iter().filter(compound).map(|(op, tokens)| {
        (
            format!("{} if glued == Some({})", kind(tokens[0]), kind(tokens[1])),
            format!("(BinaryOp::{}, 2)", op.name),
        )
    });
    let singles = operators
        .iter()
        .filter(|entry| !compound(entry))
        .map(|(op, tokens)| (kind(tokens[0]), format!("(BinaryOp::{}, 1)", op.name)));
    (glued, arms(compounds.chain(singles)))
}

/// `docs/reference/generated/grammar.md`.
pub fn reference(grammar: &Grammar) -> String {
    let shapes = [
        (Shape::Trivia, "Trivia"),
        (Shape::Ident, "Names"),
        (Shape::Keyword, "Keywords"),
        (Shape::Literal, "Literals"),
        (Shape::Punct, "Punctuation"),
        (Shape::Error, "Errors"),
    ];
    let mut tokens = String::new();
    for (shape, heading) in shapes {
        let texted = matches!(shape, Shape::Keyword | Shape::Punct);
        let header = if texted {
            ["Text", "Kind", "Classes", "Notes"]
        } else {
            ["Kind", "Reads as", "Classes", "Notes"]
        };
        let rows: Vec<Vec<String>> = grammar
            .tokens
            .iter()
            .filter(|token| token.shape == shape)
            .map(|token| {
                let (first, second) = if texted {
                    (code(text(token)), code(&token.name))
                } else {
                    (code(&token.name), cell(&token.description))
                };
                vec![first, second, classes(token), cell(&token.doc.join(" "))]
            })
            .collect();
        if !rows.is_empty() {
            tokens += &format!("### {heading}\n\n{}\n", table(&header, rows));
        }
    }
    let compounds = bullets(grammar.compounds.iter().map(|text| code(text)));
    let pairs = bullets(grammar.pairs.iter().map(|pair| {
        // A pair the lexer emits, such as a hole's braces, has kinds where
        // punctuation has text.
        let bracket = |name: &str| {
            let token = grammar.token(name).expect("validated");
            code(token.text.as_deref().unwrap_or(name))
        };
        let role = if pair.statements {
            " — encloses statements"
        } else {
            ""
        };
        format!(
            "{} … {}{role}",
            bracket(&pair.opener),
            bracket(&pair.closer)
        )
    }));
    let prefix = bullets(grammar.prefix.iter().map(|text| code(text)));
    let mut levels: Vec<u8> = grammar.binary.iter().map(|op| op.level).collect();
    levels.sort_unstable_by(|a, b| b.cmp(a));
    levels.dedup();
    let binary = table(
        &["Level", "Operators", "Notes"],
        levels.into_iter().map(|level| {
            let ops: Vec<&Binary> = grammar
                .binary
                .iter()
                .filter(|op| op.level == level)
                .collect();
            let notes = match ops.iter().filter(|op| op.comparison).count() {
                0 => "",
                n if n == ops.len() => "comparison",
                _ => "partly comparison",
            };
            let texts = list(ops.iter().map(|op| code(&op.text)), " ");
            vec![level.to_string(), texts, notes.to_owned()]
        }),
    );
    let name = |token: &Token| code(token.text.as_deref().unwrap_or(&token.name));
    let class = |member: fn(&Token) -> bool| {
        list(
            grammar
                .tokens
                .iter()
                .filter(|token| member(token))
                .map(name),
            ", ",
        )
    };
    let expr = class(|token| token.flags.expr);
    let stmt = class(|token| token.flags.stmt);
    let end = class(|token| token.flags.end);
    let item = class(|token| token.flags.item);
    let continues = class(|token| token.flags.continues);
    let spaced = list(
        grammar
            .prefix
            .iter()
            .filter(|text| grammar.binary.iter().any(|op| op.text == **text))
            .map(|text| code(text)),
        ", ",
    );
    let rules: String = grammar
        .rules
        .iter()
        .map(|rule| {
            let doc: String = rule.doc.iter().map(|line| format!("// {line}\n")).collect();
            format!("{doc}{} = {}\n", rule.name, rule.body)
        })
        .collect();
    let prefix_rule = list(grammar.prefix.iter().map(|text| format!("'{text}'")), " | ");
    let binary_rule = list(
        grammar.binary.iter().map(|op| format!("'{}'", op.text)),
        " | ",
    );
    format!(
        "# Grammar

<!-- {GENERATED} -->

Generated from [`sumi.grammar`](../../../sumi.grammar), the one declaration of
Sumi's tokens, syntax nodes, and the token classes the lexer, the newline
rule, and the parser derive from them. Edit that file and run
`cargo xtask codegen`: this chapter, the kind enums, and every derived
table follow.

## Tokens

Trivia never reaches the grammar; every other kind is a significant token.
*Reads as* is how a kind is named after \"expected\" in a diagnostic. The
*classes* are the flags declared in the grammar: `expr` can begin an
expression, `stmt` begins a statement that is not an expression, `end` lets
a statement end after it, `item` begins a top-level item, and `continue`
continues the previous line. Operators take their classes from the
[operator tables](#operators) instead.

{tokens}### Compound operators

The lexer produces single punctuation only. The parser glues these from
adjacent characters; a space between them keeps them apart.

{compounds}
## Brackets

The token stream pairs each closer with the nearest open bracket of its
kind, discarding unmatched openers above that match; an orphan closer
pairs with nothing. Grammar decides whether a pair is meaningful where it
appears. A pair that encloses statements keeps the newline rule inside
it; every other pair suspends it between its brackets.

{pairs}
## Operators

### Prefix

A prefix operator is glued to its operand, which binds tighter than any
binary operator: only a call binds closer.

{prefix}
### Binary

Every binary operator associates left and must be spaced on both sides.
Higher levels bind tighter. Comparisons do not chain: `a < b < c` is
rejected rather than parsed.

The spacing is grammar, not style: an unspaced binary operator is an
error, never a warning, because every glued form is reserved. Glued to
what follows, an operator is a prefix operator, as `-` and `!` are.
Glued to the identifier before it, `<` opens type arguments. A glued
form that means nothing yet, `a*b` or a line beginning `*b`, stays an
error so that it can be given a meaning later, as `*` for dereference
or `&` for a reference, without changing any valid program: no valid
program contains it.

{binary}
## Lines

Sumi has no `;`. A line break ends a statement when the token before it can
end one, the token after it does not continue one, and no parenthesis the
stream closes is open around it. These classes decide the first two;
the parser's spacing rules keep the third unambiguous.

- **Can begin an expression:** {expr}.
- **Begin a statement without being an expression:** {stmt}.
- **A statement can end after:** {end}.
- **Begin a top-level item:** {item}.
- **Continue the previous line:** {continues}, and any binary operator leading the line — a compound one when glued into shape, and {spaced} only when spaced from what follows, since glued it opens an operand.

## Strings

A string literal takes one of four forms. `\"…\"` and `r\"…\"` sit on one
line: a line break ends an unterminated one, so a stray quote costs its
line and nothing after it. The escapes are `\\n`, `\\r`, `\\t`, `\\\\`, `\\\"`,
`\\'`, `\\0`, and `\\u{{…}}` with one to six hex digits; a raw literal has
none, and `r#\"…\"#` lets one contain quotes.

Text that spans lines is a multi-line literal, `\"\"\"` to `\"\"\"`, or
`r\"\"\"` to `\"\"\"` with nothing escaped:

- The content begins on the line after the opening `\"\"\"`, and the
  closing `\"\"\"` begins its own line.
- Every content line begins with the closing line's indentation, which is
  not part of the value; a line of only whitespace counts as empty.
- The value keeps each line break except the one before the closing line,
  as `\\n` whatever the source uses. A `\\` ending a line joins it to the
  next.
- A `\"\"\"` inside the content escapes one of its quotes; a raw multi-line
  literal cannot contain one.

A `{{` in a `\"…\"` or `\"\"\"` literal opens a hole: an expression whose
value the string takes in its place, as in `\"{{count}} items\"`. Any
expression may stand in a hole, a string with holes of its own included,
but a hole ends with its line: one still open at the line break is an
error, and the text goes on from there in a multi-line literal and ends
with the line in a one-line one. `\\{{` and `\\}}` are braces, a `}}`
outside a hole is one too, and a raw literal has no holes.

## Syntax nodes

The shape of valid syntax, in ungrammar notation: `'text'` is a token by
its text, a capitalized name is a node kind, a token kind, or a category,
`?` is optional, `*` repeats, and `|` separates alternatives. A rule that
only lists other rules is a category, not a node kind. A `label:` before a
child names the accessor the typed views give it; an unlabeled child is
named after its kind. The tree is
error-tolerant: any part of a node may be missing, and an `{ERROR_NODE}`
node covering tokens the parser could not parse may appear anywhere.

```
{rules}
// Defined by the operator tables.
{PREFIX_OPERATOR_RULE} = {prefix_rule}
{BINARY_OPERATOR_RULE} = {binary_rule}
```
"
    )
}

/// A `///` comment per line, ready to precede an item.
fn docs(lines: &[String]) -> String {
    lines
        .iter()
        .map(|line| {
            if line.is_empty() {
                "///\n".to_owned()
            } else {
                format!("/// {line}\n")
            }
        })
        .collect()
}

/// Enum variants from `(rendered docs, name)` pairs.
fn variants(items: impl Iterator<Item = (String, String)>) -> String {
    items.map(|(doc, name)| format!("{doc}{name},\n")).collect()
}

/// Match arms from `(pattern, value)` pairs.
fn arms(items: impl Iterator<Item = (String, String)>) -> String {
    items
        .map(|(pattern, value)| format!("{pattern} => {value},\n"))
        .collect()
}

/// A `matches!` over the patterns, or `false` when there are none.
fn matches_any(subject: &str, patterns: impl Iterator<Item = String>) -> String {
    let patterns = list(patterns, " | ");
    if patterns.is_empty() {
        "false".to_owned()
    } else {
        format!("matches!({subject}, {patterns})")
    }
}

fn list(items: impl Iterator<Item = String>, separator: &str) -> String {
    items.collect::<Vec<_>>().join(separator)
}

fn text(token: &Token) -> &str {
    token
        .text
        .as_deref()
        .expect("a keyword or punctuation token has text")
}

fn kind(token: &Token) -> String {
    format!("SyntaxKind::{}", token.name)
}

fn operator_tokens<'a>(grammar: &'a Grammar, text: &str) -> Vec<&'a Token> {
    grammar.operator_tokens(text).expect("validated")
}

fn first_token<'a>(grammar: &'a Grammar, text: &str) -> &'a Token {
    operator_tokens(grammar, text)[0]
}

/// The token's flags as Markdown, in grammar-file spelling.
fn classes(token: &Token) -> String {
    let flags = token.flags;
    let set = [
        (flags.expr, "expr"),
        (flags.stmt, "stmt"),
        (flags.end, "end"),
        (flags.item, "item"),
        (flags.continues, "continue"),
    ];
    list(
        set.into_iter()
            .filter(|(set, _)| *set)
            .map(|(_, name)| code(name)),
        " ",
    )
}

fn bullets(items: impl Iterator<Item = String>) -> String {
    items.map(|item| format!("- {item}\n")).collect()
}

/// A Markdown table.
fn table(header: &[&str], rows: impl IntoIterator<Item = Vec<String>>) -> String {
    let row = |cells: Vec<String>| format!("| {} |\n", cells.join(" | "));
    let mut out = row(header.iter().map(|&cell| cell.to_owned()).collect());
    out += &row(vec!["---".to_owned(); header.len()]);
    rows.into_iter().map(row).for_each(|line| out += &line);
    out
}

/// Text inside a Markdown table cell.
fn cell(text: &str) -> String {
    text.replace('|', "\\|")
}

/// A Markdown code span, safe inside a table cell.
fn code(text: &str) -> String {
    format!("`{}`", cell(text))
}

/// `crates/syntax/src/generated/ast.rs`.
pub fn ast(grammar: &Grammar) -> String {
    let items: String = grammar
        .rules
        .iter()
        .map(|rule| {
            if grammar.is_category(rule) {
                let doc = format!("{}/// The `{}` category.\n", docs(&rule.doc), rule.name);
                view_enum(grammar, &rule.name, &doc, &alternatives(&rule.body))
            } else {
                view_struct(grammar, rule)
            }
        })
        .collect();
    format!(
        r#"//! Typed views over the syntax tree: a zero-cost wrapper per node kind,
//! with an accessor for each child the grammar names, and an enum per
//! category. A view is a [`NodeIdx`](crate::NodeIdx) with a type; every accessor takes the
//! tree, since a node carries no pointer back to it.
//!
//! Accessors answer `Option` or an iterator whatever the grammar requires,
//! because a parsed tree is error-tolerant: a node whose
//! [`SyntaxTree::has_error`](crate::SyntaxTree::has_error) bit is set may lack any child. A single-valued
//! accessor answers only what its node's children settle: every reading of
//! them that respects the rule's order and types must agree on the child,
//! or the accessor answers `None`. On a node without an error the grammar
//! fixes the reading, so every accessor is exact; on a node with one, a
//! child that could fill two fields — the lone block of `if {{}}`, which
//! could be condition or body — fills neither. The scan allocates nothing.
//! A many-valued accessor yields the children in source order, which the
//! tree stores in reverse, so it collects them once per call.
//!
//! {GENERATED}

use crate::fields;
use crate::generated::NodeKind;
use crate::index::NodeIdx;
use crate::tree::SyntaxTree;

/// A typed view over one node: what every struct and enum here implements.
pub trait AstNode: Copy {{
    /// The view over `node`, if it is of a fitting kind.
    fn cast(tree: &SyntaxTree, node: NodeIdx) -> Option<Self>;

    /// The node the view is over.
    fn node(self) -> NodeIdx;
}}

{items}"#
    )
}

/// The view over one node kind, with an accessor per field.
fn view_struct(grammar: &Grammar, rule: &Rule) -> String {
    let name = &rule.name;
    let fields = grammar.fields(rule).expect("validated");
    let doc = format!(
        "{}/// The `{name} = {}` rule.\n",
        docs(&rule.doc),
        rule.body
    );
    let mut out = format!(
        r#"{doc}#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct {name}(NodeIdx);

impl AstNode for {name} {{
    fn cast(tree: &SyntaxTree, node: NodeIdx) -> Option<Self> {{
        (tree.kind(node) == NodeKind::{name}).then_some(Self(node))
    }}

    fn node(self) -> NodeIdx {{
        self.0
    }}
}}

impl {name} {{
    pub const KIND: NodeKind = NodeKind::{name};
"#
    );
    let singles: Vec<&Field> = fields.iter().filter(|field| !field.many).collect();
    if !singles.is_empty() {
        let count = singles.len();
        let specs: String = singles
            .iter()
            .map(|field| {
                format!(
                    "fields::FieldSpec {{ fits: |tree, node| {}::cast(tree, node).is_some(), required: {} }},\n",
                    type_of(field),
                    field.required
                )
            })
            .collect();
        out += &format!(
            r#"
    /// The rule's single-valued children in order, for [`fields::assign`].
    const FIELDS: [fields::FieldSpec; {count}] = [
{specs}    ];
"#
        );
        for (slot, field) in singles.iter().enumerate() {
            let ty = type_of(field);
            let promise = if field.required {
                "present on a node without an error"
            } else {
                "optional"
            };
            out += &format!(
                r#"
    /// The `{}` child, a `{ty}`, {promise}.
    pub fn {}(self, tree: &SyntaxTree) -> Option<{ty}> {{
        fields::assign(tree, self.0, &Self::FIELDS)[{slot}].and_then(|node| {ty}::cast(tree, node))
    }}
"#,
                field.name, field.name
            );
        }
    }
    for field in fields.iter().filter(|field| field.many) {
        let ty = type_of(field);
        out += &format!(
            r#"
    /// The `{}` children, each a `{ty}`, in source order: collected once
    /// per call, since the tree stores children last first.
    pub fn {}<'t>(self, tree: &'t SyntaxTree) -> impl Iterator<Item = {ty}> + 't {{
        tree.children_in_order(self.0)
            .filter_map(move |child| {ty}::cast(tree, child))
    }}
"#,
            field.name, field.name
        );
    }
    out += "}\n\n";
    for field in &fields {
        if let FieldType::Alt(rules) = &field.ty {
            let doc = format!(
                "/// The `{}` child of `{name}`: `{}`.\n",
                field.name,
                rules.join(" | ")
            );
            out += &view_enum(grammar, &type_of(field), &doc, rules);
        }
    }
    out
}

/// One enum over several kinds: a category, or a labeled alternation.
fn view_enum(grammar: &Grammar, name: &str, doc: &str, rules: &[String]) -> String {
    let variants: String = rules
        .iter()
        .map(|rule| format!("{rule}({rule}),\n"))
        .collect();
    let is_category = |rule: &&String| {
        grammar
            .rule(rule)
            .is_some_and(|rule| grammar.is_category(rule))
    };
    let arms: String = rules
        .iter()
        .filter(|rule| !is_category(rule))
        .map(|rule| format!("NodeKind::{rule} => Some(Self::{rule}({rule}(node))),\n"))
        .collect();
    let fallback = list(
        rules
            .iter()
            .filter(is_category)
            .map(|rule| format!("{rule}::cast(tree, node).map(Self::{rule})")),
        ".or_else(|| ",
    );
    let fallback = if fallback.is_empty() {
        "None".to_owned()
    } else {
        let nested = rules.iter().filter(is_category).count() - 1;
        format!("{fallback}{}", ")".repeat(nested))
    };
    let nodes: String = rules
        .iter()
        .map(|rule| format!("Self::{rule}(inner) => inner.node(),\n"))
        .collect();
    format!(
        r#"{doc}#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum {name} {{
{variants}}}

impl AstNode for {name} {{
    fn cast(tree: &SyntaxTree, node: NodeIdx) -> Option<Self> {{
        match tree.kind(node) {{
{arms}            _ => {fallback},
        }}
    }}

    fn node(self) -> NodeIdx {{
        match self {{
{nodes}        }}
    }}
}}

"#
    )
}

fn type_of(field: &Field) -> String {
    field.ty.type_name(&field.name)
}
