//! The token vocabulary: every kind the lexer assigns, the keyword and
//! punctuation tables it classifies by, and the fixed text and diagnostic
//! description of each kind.
//!
//! @generated by `cargo xtask codegen` from `sumi.grammar`; do not edit.

/// The language-level kind of a token.
///
/// The lexer assigns these while a token's bytes are cache-hot; the
/// shape-only [`RawKind`](crate::RawKind) is stored beside them for phases
/// that reason about lexical shape. Every kind occupies a source range:
/// there is deliberately no EOF sentinel (end of input is the end of the
/// token buffer, surfaced as `Option` by lookahead APIs), and compound
/// operators are not kinds: the parser glues them from adjacent
/// punctuation.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum SyntaxKind {
    /// Horizontal whitespace, or the byte-order mark.
    Whitespace,
    /// One line break.
    Newline,
    LineComment,
    /// An identifier that is not a keyword.
    Ident,
    /// The identifier `_` on its own, reserved for discards.
    Underscore,
    ElseKw,
    FalseKw,
    FnKw,
    IfKw,
    LetKw,
    MutKw,
    ReturnKw,
    TrueKw,
    /// A decimal integer literal.
    IntLiteral,
    /// A float literal: a fraction (`1.5`), an exponent (`1e3`), or both.
    FloatLiteral,
    StringLiteral,
    RawStringLiteral,
    CharLiteral,
    LParen,
    RParen,
    LBrace,
    RBrace,
    Comma,
    Colon,
    Dot,
    Eq,
    Lt,
    Gt,
    Bang,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Amp,
    Pipe,
    /// A token with no meaning in the language: unrecognized characters,
    /// misplaced byte-order marks, and punctuation without a role.
    Error,
}

impl SyntaxKind {
    /// Every kind, in declaration order.
    pub const ALL: [Self; 37] = [
        Self::Whitespace,
        Self::Newline,
        Self::LineComment,
        Self::Ident,
        Self::Underscore,
        Self::ElseKw,
        Self::FalseKw,
        Self::FnKw,
        Self::IfKw,
        Self::LetKw,
        Self::MutKw,
        Self::ReturnKw,
        Self::TrueKw,
        Self::IntLiteral,
        Self::FloatLiteral,
        Self::StringLiteral,
        Self::RawStringLiteral,
        Self::CharLiteral,
        Self::LParen,
        Self::RParen,
        Self::LBrace,
        Self::RBrace,
        Self::Comma,
        Self::Colon,
        Self::Dot,
        Self::Eq,
        Self::Lt,
        Self::Gt,
        Self::Bang,
        Self::Plus,
        Self::Minus,
        Self::Star,
        Self::Slash,
        Self::Percent,
        Self::Amp,
        Self::Pipe,
        Self::Error,
    ];

    /// The keyword kind for `text`, if it is a reserved word.
    pub fn from_keyword(text: &str) -> Option<Self> {
        Some(match text {
            "_" => Self::Underscore,
            "else" => Self::ElseKw,
            "false" => Self::FalseKw,
            "fn" => Self::FnKw,
            "if" => Self::IfKw,
            "let" => Self::LetKw,
            "mut" => Self::MutKw,
            "return" => Self::ReturnKw,
            "true" => Self::TrueKw,
            _ => return None,
        })
    }

    /// The kind for a punctuation character, if it has a role in the
    /// language. Punctuation without one has no kind and lexes as an error
    /// token.
    pub fn from_punct(byte: u8) -> Option<Self> {
        Some(match byte {
            b'(' => Self::LParen,
            b')' => Self::RParen,
            b'{' => Self::LBrace,
            b'}' => Self::RBrace,
            b',' => Self::Comma,
            b':' => Self::Colon,
            b'.' => Self::Dot,
            b'=' => Self::Eq,
            b'<' => Self::Lt,
            b'>' => Self::Gt,
            b'!' => Self::Bang,
            b'+' => Self::Plus,
            b'-' => Self::Minus,
            b'*' => Self::Star,
            b'/' => Self::Slash,
            b'%' => Self::Percent,
            b'&' => Self::Amp,
            b'|' => Self::Pipe,
            _ => return None,
        })
    }

    /// The fixed text of a keyword or punctuation kind; `None` for kinds
    /// whose text varies.
    pub fn text(self) -> Option<&'static str> {
        Some(match self {
            Self::Underscore => "_",
            Self::ElseKw => "else",
            Self::FalseKw => "false",
            Self::FnKw => "fn",
            Self::IfKw => "if",
            Self::LetKw => "let",
            Self::MutKw => "mut",
            Self::ReturnKw => "return",
            Self::TrueKw => "true",
            Self::LParen => "(",
            Self::RParen => ")",
            Self::LBrace => "{",
            Self::RBrace => "}",
            Self::Comma => ",",
            Self::Colon => ":",
            Self::Dot => ".",
            Self::Eq => "=",
            Self::Lt => "<",
            Self::Gt => ">",
            Self::Bang => "!",
            Self::Plus => "+",
            Self::Minus => "-",
            Self::Star => "*",
            Self::Slash => "/",
            Self::Percent => "%",
            Self::Amp => "&",
            Self::Pipe => "|",
            _ => return None,
        })
    }

    /// Whether the kind is trivia — whitespace, line breaks, and comments —
    /// which the grammar never sees.
    pub fn is_trivia(self) -> bool {
        matches!(self, Self::Whitespace | Self::Newline | Self::LineComment)
    }

    /// How the kind reads as the object of "expected" in a diagnostic.
    pub fn describe(self) -> &'static str {
        match self {
            Self::Whitespace => "whitespace",
            Self::Newline => "a line break",
            Self::LineComment => "a line comment",
            Self::Ident => "a name",
            Self::Underscore => "`_`",
            Self::ElseKw => "`else`",
            Self::FalseKw => "`false`",
            Self::FnKw => "`fn`",
            Self::IfKw => "`if`",
            Self::LetKw => "`let`",
            Self::MutKw => "`mut`",
            Self::ReturnKw => "`return`",
            Self::TrueKw => "`true`",
            Self::IntLiteral => "an integer literal",
            Self::FloatLiteral => "a floating-point literal",
            Self::StringLiteral => "a string literal",
            Self::RawStringLiteral => "a raw string literal",
            Self::CharLiteral => "a character literal",
            Self::LParen => "`(`",
            Self::RParen => "`)`",
            Self::LBrace => "`{`",
            Self::RBrace => "`}`",
            Self::Comma => "`,`",
            Self::Colon => "`:`",
            Self::Dot => "`.`",
            Self::Eq => "`=`",
            Self::Lt => "`<`",
            Self::Gt => "`>`",
            Self::Bang => "`!`",
            Self::Plus => "`+`",
            Self::Minus => "`-`",
            Self::Star => "`*`",
            Self::Slash => "`/`",
            Self::Percent => "`%`",
            Self::Amp => "`&`",
            Self::Pipe => "`|`",
            Self::Error => "valid syntax",
        }
    }
}
